### ISSUE TITLE
About the original PoinTr

### ISSUE THREAD

**Issue by yuluoxingchen111** [tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks#2]
Excuse me, when I made my building point cloud data into a PCN dataset and trained it in the original PoinTr with KITTI configuration, the result was very poor, and there was no significant change after modifying the parameters. Is this situation because my data was not well made? (I directly replaced the Cars in the original model KITTI dataset with self-made data, and created new. yaml configuration files and JSON files.)

**Comment by WeixiaoGao** [comment]
It sounds like your issue isn't directly related to our repository. If you're training with your own data and configuring the related data files yourself, it might be difficult for me to pinpoint the problem. From my tests, the results of PoinTr on completing simple buildings are acceptable.

**Comment by yuluoxingchen111** [comment]
> 听起来您的问题与我们的存储库没有直接关系。如果您使用自己的数据进行训练并自己配置相关数据文件，我可能很难确定问题所在。根据我的测试，PoinTr 完成简单建筑的结果是可以接受的。

Yes, I have been trying to train my dataset on PoinTr before studying your paper, but I have not been able to achieve the desired results.
I expand dozens of original point clouds into thousands through rotation and scaling, and then use this as the initial input point cloud. Firstly, normalize these input point clouds to [-0.5,0.5], then downsample to 16384 points and store them as complete point clouds in complete. Then, crop the downsampled point clouds to obtain partial point clouds and store them in partial. Next, continue cropping the point cloud under the partial to obtain the incomplete point cloud stored in KITTI. Finally, calculate the boundary vertex coordinates of each incomplete point cloud based on the incomplete point cloud and save them to the bboxes folder in KITTI. Thus obtaining all the necessary data.
The cropping method is to select a point outside the point cloud as a reference point, and save the n points closest to it (referring to the "randomly selecting 8 perspectives" mentioned in PoinTr's paper). The saved file format is. pcd file.
And, I directly created a new data folder and used the original KITTI car ID 02958343 to represent the building. The original point cloud I used consisted of 66 independent buildings, but these 66 buildings would form a residential area. Where do you think my problem may lie?

**Comment by yuluoxingchen111** [comment]
> > 听起来您的问题与我们的存储库没有直接关系。如果您使用自己的数据进行训练并自己配置相关数据文件，我可能很难确定问题所在。根据我的测试，PoinTr 完成简单建筑的结果是可以接受的。
> 
> Yes, I have been trying to train my dataset on PoinTr before studying your paper, but I have not been able to achieve the desired results. I expand dozens of original point clouds into thousands through rotation and scaling, and then use this as the initial input point cloud. Firstly, normalize these input point clouds to [-0.5,0.5], then downsample to 16384 points and store them as complete point clouds in complete. Then, crop the downsampled point clouds to obtain partial point clouds and store them in partial. Next, continue cropping the point cloud under the partial to obtain the incomplete point cloud stored in KITTI. Finally, calculate the boundary vertex coordinates of each incomplete point cloud based on the incomplete point cloud and save them to the bboxes folder in KITTI. Thus obtaining all the necessary data. The cropping method is to select a point outside the point cloud as a reference point, and save the n points closest to it (referring to the "randomly selecting 8 perspectives" mentioned in PoinTr's paper). The saved file format is. pcd file. And, I directly created a new data folder and used the original KITTI car ID 02958343 to represent the building. The original point cloud I used consisted of 66 independent buildings, but these 66 buildings would form a residential area. Where do you think my problem may lie?

May I ask if you have tested training the PCN building dataset in. pcd format on PoinTr? If so, can you provide the dataset you are using? Thank you very much.

**Comment by WeixiaoGao** [comment]
It sounds like there's nothing wrong with your process, and I don't think the issue lies with your data. Are your results on the validation dataset also poor? I haven't tested the PCN architecture data.
