### ISSUE TITLE
Problems encountered during training

### ISSUE THREAD

**Issue by yuluoxingchen111** [tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks#3]
I have configured the environment and run install.sh, requirements.txt, installed pointnet2_ops, and stored the data. But when I was training the data in BuildingPCC-NL_40_demo that you provided, the data I obtained was abnormal.

![QQ图片20240512020457](https://github.com/tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks/assets/131221039/d1f8c3af-1d74-4ba4-b6db-0c78b83b5159)

**Comment by yuluoxingchen111** [comment]
> I have configured the environment and run install.sh, requirements.txt, installed pointnet2_ops, and stored the data. But when I was training the data in BuildingPCC-NL_40_demo that you provided, the data I obtained was abnormal.
> 
> ![QQ图片20240512020457](https://private-user-images.githubusercontent.com/131221039/329805533-d1f8c3af-1d74-4ba4-b6db-0c78b83b5159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTEzMjEsIm5iZiI6MTcxNTQ1MTAyMSwicGF0aCI6Ii8xMzEyMjEwMzkvMzI5ODA1NTMzLWQxZjhjM2FmLTFkNzQtNGJhNC1iNmRiLTBjNzhiODNiNTE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxODEwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjU3MTZjYzIwMDZhMmIzYTA1MTUzMTE1MzFhNzhmYzg0NTgwNDBiM2U3M2Y4YzZmYjg0M2ZkOGMwMTAwZGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3QOeyP_4-0CvYfCxQoEIHU285XIH2tYjnEDcNjPmYPc)

Do I need to perform any data processing before training?

**Comment by WeixiaoGao** [comment]
The demo data only includes a few dozen buildings, and I'm not sure if this amount is sufficient for training. You might want to try testing with a pre-trained model first. The data we provide does not require additional processing; please use the script we provided to process the BuildingNL data.

**Comment by yuluoxingchen111** [comment]
I use the pre-trained model for testing:bash ./scripts/test.sh 0 \
    --ckpts ./ckpts/BNL_50k_300e/ckpt-best.pth \
    --config ./cfgs/BuildingNL_models/PoinTr.yaml \
    --exp_name example

This is the result of the first batch：
![image](https://github.com/tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks/assets/131221039/9e86b563-becf-4739-a344-e04aa52ce139)

**Comment by yuluoxingchen111** [comment]
I noticed that the code you provided does not include main.py, so I directly used the original PoinTr's main.py.

**Comment by yuluoxingchen111** [comment]
When I use this command:
bash ./scripts/train.sh 0 \
    --config ./cfgs/BuildingNL_models/PoinTr.yaml \
    --exp_name example002

The output is as follows:
![image](https://github.com/tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks/assets/131221039/a813b38d-59cc-43bb-a9f2-7c652ea09ba8)
There are obvious anomalies in the data.

**Comment by yuluoxingchen111** [comment]
Excuse me, do you have a solution to the above problem? And, main.py may require you to provide it separately. @WeixiaoGao

**Comment by WeixiaoGao** [comment]
I've added main.py, which strangely is missing somehow in the first place. In fact, it's the same as the original PoinTr and I haven't changed it. I can't tell from the screenshot what is causing your problem. But I have attached my training log and parameter settings on PoinTr you can refer to it.
[pointrlog.zip](https://github.com/tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks/files/15413973/pointrlog.zip)

**Comment by yuluoxingchen111** [comment]
Yes, the strange thing is that I set the same data structure and configuration parameters, but generated abnormal results. I haven't made any other changes.

**Comment by yuluoxingchen111** [comment]
![image](https://github.com/tudelft3d/Building-PCC-Building-Point-Cloud-Completion-Benchmarks/assets/131221039/c4f84e7e-60bc-43f9-8890-84423a30f46f)
It seems that you did not provide this file.

**Comment by WeixiaoGao** [comment]
Thank you for pointing this out. I may have initially uploaded the wrong folder and caused the file to be missing. My apologies. I have updated all the files. Please let me know if you find anything else missing or incorrect.

**Comment by yuluoxingchen111** [comment]
Do I only need to download pre_norm_params. py? I don't want to download the entire library again.

**Comment by WeixiaoGao** [comment]
I suggest you pull the project to get all the updated files. Otherwise, you can only download the updated files by checking for commits.

**Comment by yuluoxingchen111** [comment]
OK
